### ISSUE TITLE
About agent step method's return values

### ISSUE THREAD

**Issue by GWFrank** [cwlin1998/reversi-pygame#41] opened 2020-12-02 18:01 UTC
I'm not sure if this is a feature or a bug.
If I want my agent to make a move at [D3], instead of returning tuple `(3, 2)` or `(4, 3)`, I have to return something like `(267, 219)`.
Is this board-coordinate-to-pixel-coordinate part of our job?  The doc string of BaseAgent didn't mention this.

**Comment by cwlin1998** [comment] 2020-12-02 18:15
Hmm... you should be able to figure out how it transferred by reading the step function in RandomAgent.
However, that's something we didn't expect you to focus on. Therefore, the following is the code transferring the index of the block to the coordinate on the screen. (Or you can copy the last three line as the transferring from tuple to coordinate.)

``` python
def index2pos(self, index):
    row_index = index // self.cols_n
    col_index = index % self.cols_n
    x = self.col_offset + col_index * self.block_len
    y = self.row_offset + row_index * self.block_len
    return x, y
```

**Comment by cwlin1998** [comment] 2020-12-02 18:17
By the way, it's a feature. XD
Since the game is initially designed for human, the input was designed to be the input coordinate the player clicked.

**Closed** 2020-12-03 00:30 UTC
